/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public class Evh extends AbstractEvh { 
	public Evh(String name, ActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
