/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobot;
import alice.tuprolog.Term;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.contactEvent.platform.EventHandlerComponent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public abstract class AbstractEvh extends EventHandlerComponent { //implements IActionHandler
protected IEventItem event;
	public AbstractEvh(String name, ActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, eventIds, outEnvView);
  	}
	@Override
	public void doJob() throws Exception {
		event = getEventItem();
		if( event == null ) return;
		myCtx.getActor("qarobotcontroller").solveGoal("assert(harmful)",0,"","","");
	}
}
