/* Generated by AN DISI Unibo */ 
package it.unibo.qarobotexecutor;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;
public class Qarobotexecutor extends AbstractQarobotexecutor { 
	public Qarobotexecutor(String actorId, ActorContext myCtx, IOutputEnvView outEnvView ,it.unibo.iot.executors.baseRobot.IBaseRobot baserobot) throws Exception{
		super(actorId,myCtx,outEnvView ,baserobot );
	}
}
