/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.asc;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public class Asc extends AbstractAsc { 
	public Asc(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
